/*
 *  Tuan Anh Nguyen.  Email: t.nguyen@latrobe.edu.au
 * Computer Science & Computer Engineering Department
 * La Trobe University, VIC, 3086
 */

/*
 * SPARQLQueryBuilder.java
 *
 * Created on 20/12/2009, 12:10:29 PM
 */

package placecommframework.knowledgebase;

import java.io.*;

import java.util.ArrayList;
import java.util.Collection;
import java.util.Iterator;
import java.util.List;
import java.util.ListIterator;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.xml.parsers.*;
import org.w3c.dom.*;
import com.hp.hpl.jena.query.*;

import placecommframework.knowledgebase.PredefinedQueries;
import utilities.MessageBoxDlg;



/**
 *
 * @author Tuan Nguyen
 */
public class SPARQLQueryBuilder extends javax.swing.JDialog {

    /** Creates new form SPARQLQueryBuilder */
    public SPARQLQueryBuilder(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tfSelectSubject = new javax.swing.JTextField();
        tfSelectObject = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tfWhereSubject1 = new javax.swing.JTextField();
        tfWhereObject1 = new javax.swing.JTextField();
        cbbPredicate1 = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tfFilter = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        taSparqlQuery = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        btGenerateSPARQL = new javax.swing.JButton();
        btParseSPARQL = new javax.swing.JButton();
        btExecute = new javax.swing.JButton();
        btClear = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tfWhereSubject2 = new javax.swing.JTextField();
        cbbPredicate2 = new javax.swing.JComboBox();
        tfWhereObject2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tfWhereSubject3 = new javax.swing.JTextField();
        cbbPredicate3 = new javax.swing.JComboBox();
        tfWhereObject3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tfWhereSubject4 = new javax.swing.JTextField();
        cbbPredicate4 = new javax.swing.JComboBox();
        tfWhereObject4 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tfWhereSubject5 = new javax.swing.JTextField();
        cbbPredicate5 = new javax.swing.JComboBox();
        tfWhereObject5 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstPrefix = new javax.swing.JList();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        tfTimestamp2 = new javax.swing.JTextField();
        tfTimestamp1 = new javax.swing.JTextField();
        cbTimeConcern = new javax.swing.JCheckBox();
        cbbPredefinedQuerries = new javax.swing.JComboBox();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("Form"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(placecommframework.PlaceCommFrameworkApp.class).getContext().getResourceMap(SPARQLQueryBuilder.class);
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        tfSelectSubject.setText(resourceMap.getString("tfSelectSubject.text")); // NOI18N
        tfSelectSubject.setName("tfSelectSubject"); // NOI18N

        tfSelectObject.setText(resourceMap.getString("tfSelectObject.text")); // NOI18N
        tfSelectObject.setName("tfSelectObject"); // NOI18N

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        tfWhereSubject1.setText(resourceMap.getString("tfWhereSubject1.text")); // NOI18N
        tfWhereSubject1.setName("tfWhereSubject1"); // NOI18N

        tfWhereObject1.setText(resourceMap.getString("tfWhereObject1.text")); // NOI18N
        tfWhereObject1.setName("tfWhereObject1"); // NOI18N

        cbbPredicate1.setEditable(true);
        cbbPredicate1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "rdfs:", "swrl:", "protege:", "foaf:", "dev:", "xsp:", "swrlb:", "xsd:", "owl:", "rdf:", "pbvc:", "plc:" }));
        cbbPredicate1.setName("cbbPredicate1"); // NOI18N

        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        jLabel8.setText(resourceMap.getString("jLabel8.text")); // NOI18N
        jLabel8.setName("jLabel8"); // NOI18N

        tfFilter.setText(resourceMap.getString("tfFilter.text")); // NOI18N
        tfFilter.setName("tfFilter"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        taSparqlQuery.setColumns(20);
        taSparqlQuery.setRows(5);
        taSparqlQuery.setName("taSparqlQuery"); // NOI18N
        jScrollPane1.setViewportView(taSparqlQuery);

        jLabel9.setText(resourceMap.getString("jLabel9.text")); // NOI18N
        jLabel9.setName("jLabel9"); // NOI18N

        btGenerateSPARQL.setText(resourceMap.getString("btGenerateSPARQL.text")); // NOI18N
        btGenerateSPARQL.setName("btGenerateSPARQL"); // NOI18N
        btGenerateSPARQL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btGenerateSPARQLMouseClicked(evt);
            }
        });

        btParseSPARQL.setText(resourceMap.getString("btParseSPARQL.text")); // NOI18N
        btParseSPARQL.setName("btParseSPARQL"); // NOI18N
        btParseSPARQL.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                btParseSPARQLMouseWheelMoved(evt);
            }
        });
        btParseSPARQL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btParseSPARQLMouseClicked(evt);
            }
        });

        btExecute.setText(resourceMap.getString("btExecute.text")); // NOI18N
        btExecute.setName("btExecute"); // NOI18N
        btExecute.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btExecuteMouseClicked(evt);
            }
        });

        btClear.setText(resourceMap.getString("btClear.text")); // NOI18N
        btClear.setName("btClear"); // NOI18N
        btClear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btClearMouseClicked(evt);
            }
        });

        jLabel10.setText(resourceMap.getString("jLabel10.text")); // NOI18N
        jLabel10.setName("jLabel10"); // NOI18N

        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N

        tfWhereSubject2.setName("tfWhereSubject2"); // NOI18N

        cbbPredicate2.setEditable(true);
        cbbPredicate2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "plc:", "rdfs:", "swrl:", "protege:", "foaf:", "dev:", "xsp:", "swrlb:", "xsd:", "owl:", "rdf:", "pbvc:" }));
        cbbPredicate2.setName("cbbPredicate2"); // NOI18N

        tfWhereObject2.setText(resourceMap.getString("tfWhereObject2.text")); // NOI18N
        tfWhereObject2.setName("tfWhereObject2"); // NOI18N

        jLabel5.setText(resourceMap.getString("jLabel5.text")); // NOI18N
        jLabel5.setName("jLabel5"); // NOI18N

        tfWhereSubject3.setName("tfWhereSubject3"); // NOI18N

        cbbPredicate3.setEditable(true);
        cbbPredicate3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "swrl:", "protege:", "foaf:", "dev:", "xsp:", "swrlb:", "xsd:", "owl:", "rdf:", "rdfs:", "pbvc:", "plc:" }));
        cbbPredicate3.setName("cbbPredicate3"); // NOI18N

        tfWhereObject3.setText(resourceMap.getString("tfWhereObject3.text")); // NOI18N
        tfWhereObject3.setName("tfWhereObject3"); // NOI18N

        jLabel6.setText(resourceMap.getString("jLabel6.text")); // NOI18N
        jLabel6.setName("jLabel6"); // NOI18N

        tfWhereSubject4.setName("tfWhereSubject4"); // NOI18N

        cbbPredicate4.setEditable(true);
        cbbPredicate4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "protege:", "swrl:", "foaf:", "dev:", "xsp:", "swrlb:", "xsd:", "owl:", "rdf:", "rdfs:", "pbvc:", "plc:", " " }));
        cbbPredicate4.setName("cbbPredicate4"); // NOI18N

        tfWhereObject4.setText(resourceMap.getString("tfWhereObject4.text")); // NOI18N
        tfWhereObject4.setName("tfWhereObject4"); // NOI18N

        jLabel7.setText(resourceMap.getString("jLabel7.text")); // NOI18N
        jLabel7.setName("jLabel7"); // NOI18N

        tfWhereSubject5.setName("tfWhereSubject5"); // NOI18N

        cbbPredicate5.setEditable(true);
        cbbPredicate5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "owl:", "protege:", "swrl:", "foaf:", "dev:", "xsp:", "swrlb:", "xsd:", "rdf:", "rdfs:", "pbvc:", "plc:", " " }));
        cbbPredicate5.setName("cbbPredicate5"); // NOI18N

        tfWhereObject5.setText(resourceMap.getString("tfWhereObject5.text")); // NOI18N
        tfWhereObject5.setName("tfWhereObject5"); // NOI18N

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        lstPrefix.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "PREFIX plc:<http://www.tuannguyen.mobi/ontologies/pbvc/2009/4/place.owl#>", "PREFIX rdfs:<http://www.w3.org/2000/01/rdf-schema#>", "PREFIX swrl:<http://www.w3.org/2003/11/swrl#>", "PREFIX protege:<http://protege.stanford.edu/plugins/owl/protege#>", "PREFIX foaf:<http://xmlns.com/foaf/0.1/>", "PREFIX dev:<http://www.tuannguyen.mobi/ontologies/pbvc/2009/4/device.owl#>", "PREFIX xsp:<http://www.owl-ontologies.com/2005/08/07/xsp.owl#>", "PREFIX swrlb:<http://www.w3.org/2003/11/swrlb#>", "PREFIX xsd:<http://www.w3.org/2001/XMLSchema#>", "PREFIX owl:<http://www.w3.org/2002/07/owl#>", "PREFIX rdf:<http://www.w3.org/1999/02/22-rdf-syntax-ns#>", "PREFIX pbvc:<http://www.tuannguyen.mobi/ontologies/pbvc/2009/4/pbvc.owl#>" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        lstPrefix.setName("lstPrefix"); // NOI18N
        jScrollPane2.setViewportView(lstPrefix);

        jLabel11.setText(resourceMap.getString("jLabel11.text")); // NOI18N
        jLabel11.setName("jLabel11"); // NOI18N

        jLabel12.setText(resourceMap.getString("jLabel12.text")); // NOI18N
        jLabel12.setName("jLabel12"); // NOI18N

        tfTimestamp2.setText(resourceMap.getString("tfTimestamp2.text")); // NOI18N
        tfTimestamp2.setName("tfTimestamp2"); // NOI18N

        tfTimestamp1.setText(resourceMap.getString("tfTimestamp1.text")); // NOI18N
        tfTimestamp1.setName("tfTimestamp1"); // NOI18N

        cbTimeConcern.setSelected(true);
        cbTimeConcern.setText(resourceMap.getString("cbTimeConcern.text")); // NOI18N
        cbTimeConcern.setName("cbTimeConcern"); // NOI18N

        cbbPredefinedQuerries.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Query1", "Query2", "Query3", "Query4", "Query5", "Query6", "Query7", "Query8", "Query9", "Query10", "Query11", "Query12", "Query13", "Query14", "Query15", "Query16", "Query17", "Query18", "Query19", "Query20", "Query21", "Query22", "Query23", "Query24", "Query25", "Query26", "Query27", "Query28", "Query29", "Query30", "Query31", "Query32", "Query33", "Query34", " " }));
        cbbPredefinedQuerries.setName("cbbPredefinedQuerries"); // NOI18N
        cbbPredefinedQuerries.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbbPredefinedQuerriesItemStateChanged(evt);
            }
        });
        cbbPredefinedQuerries.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                cbbPredefinedQuerriesPropertyChange(evt);
            }
        });

        jLabel13.setText(resourceMap.getString("jLabel13.text")); // NOI18N
        jLabel13.setName("jLabel13"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btGenerateSPARQL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btParseSPARQL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btExecute)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btClear))
                    .addComponent(jLabel13)
                    .addComponent(cbbPredefinedQuerries, 0, 419, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfWhereSubject2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbbPredicate2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfWhereObject2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfWhereSubject3, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbbPredicate3, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfWhereObject3, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfWhereSubject4, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbbPredicate4, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfWhereObject4, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfSelectSubject, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfSelectObject, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfWhereSubject1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cbbPredicate1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tfWhereObject1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(cbTimeConcern))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(tfTimestamp1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(tfTimestamp2, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)))
                            .addComponent(tfFilter, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfWhereSubject5, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbbPredicate5, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfWhereObject5, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 419, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 389, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfSelectSubject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfSelectObject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfWhereSubject1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfWhereObject1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbbPredicate1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfWhereSubject2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfWhereObject2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbbPredicate2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tfWhereSubject3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfWhereObject3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbbPredicate3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tfWhereSubject4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfWhereObject4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbbPredicate4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tfWhereSubject5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfWhereObject5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbbPredicate5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tfFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfTimestamp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbTimeConcern)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(tfTimestamp2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbbPredefinedQuerries, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btGenerateSPARQL)
                    .addComponent(btParseSPARQL)
                    .addComponent(btExecute)
                    .addComponent(btClear))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private String getPrefixValue(){
        String temp="";

        Object[] mObj  = lstPrefix.getSelectedValues();
        for (int i=0; i<mObj.length; i++){
           temp = temp + mObj[i].toString() + "\n";
        }
      return temp;
    }

    private String getPredicateCombobox(javax.swing.JComboBox cbb ){
    String str="";

        if (cbb.getSelectedItem() !=null){
          str=cbb.getEditor().getItem().toString();
        }
    return str.trim();
    }

    private String getTimeConcerns(){
    String str="";
        if (cbTimeConcern.isSelected()){
            str=" \n && (("+ tfTimestamp1.getText()+" <" +tfWhereObject5.getText()+")&&\n("
                    +tfWhereObject5.getText() +" <" +tfTimestamp2.getText()+"))";
        }
    return str;
    }

    private void btGenerateSPARQLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btGenerateSPARQLMouseClicked
        // TODO add your handling code here:
        String strTimeConcern=getTimeConcerns();
        String strSparqlQuery = getPrefixValue()+        
                " SELECT " +tfSelectSubject.getText()+" " + tfSelectObject.getText() +" \n"
               +" WHERE {" +tfWhereSubject1.getText() +  " " + getPredicateCombobox(cbbPredicate1) +  " " +  tfWhereObject1.getText()+ "  \n"
                        +tfWhereSubject2.getText() +  " " + getPredicateCombobox(cbbPredicate2) +  " " +  tfWhereObject2.getText()+ "  \n"
                        +tfWhereSubject3.getText() +  " " + getPredicateCombobox(cbbPredicate3) +  " " +  tfWhereObject3.getText()+ "  \n"
                        +tfWhereSubject4.getText() +  " " + getPredicateCombobox(cbbPredicate4) +  " " +  tfWhereObject4.getText()+ "  \n"
                        +tfWhereSubject5.getText() +  " " + getPredicateCombobox(cbbPredicate5) +  " " +  tfWhereObject5.getText()+ "  \n"
                        +" FILTER ( " +   tfFilter.getText() +strTimeConcern +")  } ";
        taSparqlQuery.setText(strSparqlQuery);
    }//GEN-LAST:event_btGenerateSPARQLMouseClicked

    private void putPredefinedQueriesToComboBox(int iSize){
        
        String[] mString2 = new String[iSize];

        for (int i=0;i <iSize; i++){
            mString2[i]=pdq[i].getQueryPlaintext();
        }

        javax.swing.DefaultComboBoxModel mModel =new javax.swing.DefaultComboBoxModel(mString2);
        cbbPredefinedQuerries.setModel(mModel);
        
    }

    
    private void cbbPredefinedQuerriesPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_cbbPredefinedQuerriesPropertyChange
        // TODO add your handling code here:
      //  loadQueriesFromFileTocbbPredefinedQuerries("d:\\MyPhd\\NewNetbeans\\placecommframework\\data\\queries.xml");


    }//GEN-LAST:event_cbbPredefinedQuerriesPropertyChange

    private String getQueryFromFile(String sFilename){
        String strQuery="", text;        
        BufferedReader reader = null;
        File file=new File(sFilename) ;
        try {

            reader = new BufferedReader(new FileReader(file));
            // repeat until all lines is read
            while ((text = reader.readLine()) != null){
                //contents.append(text).append(System.getProperty("line.separator"));
                strQuery= strQuery+text+"\n";
            }
            //System.out.println(strQuery);
            
        } catch (Exception ex) {
            Logger.getLogger(SPARQLQueryBuilder.class.getName()).log(Level.SEVERE, null, ex);
        }
        return strQuery;
    }

    private void loadQueriesFromFileTocbbPredefinedQuerries(String filename){
        // Try to look for queries.xml file
        try {
            File file = new File(filename);
            // Obtain a new instance of a DocumentBuilderFactory.
            DocumentBuilderFactory dbf =DocumentBuilderFactory.newInstance();
            
            // Get the DocumentBuilder
            DocumentBuilder db = dbf.newDocumentBuilder();
            // Parse the content of the given file as an XML document.
            Document doc = db.parse(file);
            // Get a NodeList of all the Elements with tag name “query”.
            NodeList QueryList =doc.getElementsByTagName("query");
            // Get the number of nodes i.e. “Employee” in the list.
            System.out.println("Number "+ QueryList.getLength()+ " queries.\n");
            System.out.println("Employee Information List");
            System.out.println("————————————");
            int iSize=QueryList.getLength();

            pdq =new  PredefinedQueries[iSize];

            for (int index = 0; index < QueryList.getLength(); index++) {
                // Go to the indexth item
                Node node = QueryList.item(index);
                // Check whether the node is an Element.
                if (node.getNodeType() == Node.ELEMENT_NODE) {
                    Element element = (Element) node;
                    // Get a NodeList of all descendant Elements with tag name “plaintext”
                    NodeList QueryElmntLst =element.getElementsByTagName("plaintext");
                    Element EIDElmnt = (Element)QueryElmntLst.item(0);
                    NodeList EID = EIDElmnt.getChildNodes();
                    System.out.println("Query: " + ((Node) EID.item(0)).getNodeValue());
                    pdq[index].setQueryPlaintext(((Node) EID.item(0)).getNodeValue());

                    // Get a NodeList of all descendant Elements with tag name “Emp_Name”
                    NodeList QueryFileLst =element.getElementsByTagName("file");
                    Element ENameElmnt = (Element)QueryFileLst.item(0);
                    NodeList EName = ENameElmnt.getChildNodes();
                    System.out.println("filename: " + ((Node) EName.item(0)).getNodeValue());
                    pdq[index].setQueryFile(((Node) EName.item(0)).getNodeValue());
                }
            }
            putPredefinedQueriesToComboBox(iSize);
            }catch(Exception e){
                System.out.println("File not found");
        }
    }
    private void cbbPredefinedQuerriesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbbPredefinedQuerriesItemStateChanged
        // TODO add your handling code here:

        loadQueriesFromFileTocbbPredefinedQuerries("d:/MyPhd/NewNetbeans/placecommframework/data/queries.xml");

        String str=cbbPredefinedQuerries.getModel().getSelectedItem().toString();
        taSparqlQuery.setText(str);
        //String strQuery=getQueryFromFile(str);
        //taSparqlQuery.setText(strQuery);

        

    }//GEN-LAST:event_cbbPredefinedQuerriesItemStateChanged

    private void btParseSPARQLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btParseSPARQLMouseClicked
        // TODO add your handling code here:
        //com.hp.hpl.jena.query.
        String queryString=taSparqlQuery.getText();
        try{
        Query query = QueryFactory.create(queryString) ;

        MessageBoxDlg dlg=new MessageBoxDlg(null,true, "Query OK!","SPARQL OK!");
        dlg.setVisible(true);

        }catch (QueryParseException e){
            //System.out.println("PBVC Query Exception:"+e.toString());
            Logger.getLogger(SPARQLQueryBuilder.class.getName()).log(Level.INFO, null, e);
            MessageBoxDlg dlg=new MessageBoxDlg(null,true, "PBVC Query Exception:",e.toString());
             dlg.setVisible(true);
             
            
        }


    }//GEN-LAST:event_btParseSPARQLMouseClicked

    private void btClearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btClearMouseClicked
        // TODO add your handling code here:
         taSparqlQuery.setText("");
         tfFilter.setText("");
      tfSelectObject.setText("");
      tfSelectSubject.setText("");
      tfTimestamp1.setText("");
      tfTimestamp2.setText("");
      tfWhereObject1.setText("");
      tfWhereObject2.setText("");
      tfWhereObject3.setText("");
      tfWhereObject4.setText("");
      tfWhereObject5.setText("");
      tfWhereSubject1.setText("");
      tfWhereSubject2.setText("");
      tfWhereSubject3.setText("");
      tfWhereSubject4.setText("");
      tfWhereSubject5.setText("");
    }//GEN-LAST:event_btClearMouseClicked

    private void btExecuteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btExecuteMouseClicked
        // TODO add your handling code here:


        /*
        FileReader owlFile = new FileReader(sURI); //// Query model from file
        JenaOWLModel owlModel  = ProtegeOWL.createJenaOWLModelFromReader(owlFile);
        QueryResults results = owlModel.executeSPARQLQuery(query);
        */
        /////////////////////////////////////
        /*
         /////// or Model is created or inherited from the parent project,
         // Then start query 
          Model model = ... ;
          String queryString = " .... " ;
          Query query = QueryFactory.create(queryString) ;
          QueryExecution qexec = QueryExecutionFactory.create(query, model) ;
          try {
            ResultSet results = qexec.execSelect() ;
            for ( ; results.hasNext() ; )
            {
              QuerySolution soln = results.nextSolution() ;
              RDFNode x = soln.get("varName") ;       // Get a result variable by name.
              Resource r = soln.getResource("VarR") ; // Get a result variable - must be a resource
              Literal l = soln.getLiteral("VarL") ;   // Get a result variable - must be a literal
            }
          } finally { qexec.close() ; }
         */
         MessageBoxDlg dlg=new MessageBoxDlg(null,true, "Query OK!","Results here");
         dlg.setVisible(true);
    }//GEN-LAST:event_btExecuteMouseClicked

    private void btParseSPARQLMouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_btParseSPARQLMouseWheelMoved
        // TODO add your handling code here:
        int i=evt.MOUSE_WHEEL;
        System.out.println("Mouse wheel: "+i);
    }//GEN-LAST:event_btParseSPARQLMouseWheelMoved

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SPARQLQueryBuilder dialog = new SPARQLQueryBuilder(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // <editor-fold defaultstate="collapsed" desc="Variables declaration">
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btClear;
    private javax.swing.JButton btExecute;
    private javax.swing.JButton btGenerateSPARQL;
    private javax.swing.JButton btParseSPARQL;
    private javax.swing.JCheckBox cbTimeConcern;
    private javax.swing.JComboBox cbbPredefinedQuerries;
    private javax.swing.JComboBox cbbPredicate1;
    private javax.swing.JComboBox cbbPredicate2;
    private javax.swing.JComboBox cbbPredicate3;
    private javax.swing.JComboBox cbbPredicate4;
    private javax.swing.JComboBox cbbPredicate5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList lstPrefix;
    private javax.swing.JTextArea taSparqlQuery;
    private javax.swing.JTextField tfFilter;
    private javax.swing.JTextField tfSelectObject;
    private javax.swing.JTextField tfSelectSubject;
    private javax.swing.JTextField tfTimestamp1;
    private javax.swing.JTextField tfTimestamp2;
    private javax.swing.JTextField tfWhereObject1;
    private javax.swing.JTextField tfWhereObject2;
    private javax.swing.JTextField tfWhereObject3;
    private javax.swing.JTextField tfWhereObject4;
    private javax.swing.JTextField tfWhereObject5;
    private javax.swing.JTextField tfWhereSubject1;
    private javax.swing.JTextField tfWhereSubject2;
    private javax.swing.JTextField tfWhereSubject3;
    private javax.swing.JTextField tfWhereSubject4;
    private javax.swing.JTextField tfWhereSubject5;
    // End of variables declaration//GEN-END:variables
    // </editor-fold>

    private PredefinedQueries pdq[];
    private Document dom;
}
